# CI for 
#trigger: none

pool:
  name: Azure Pipelines 
    
resources:
  repositories:
    - repository: self
      type: git
      ref: $(Build.SourceBranch)  
    - repository: ETLSharedOps
      type: git
      name: ETLSharedOps
      ref: $(Build.SourceBranch)

name: 1.0.$(Date:yyyyMMdd)$(Rev:.r)

stages:
  - template: ../.pipelines/templates/ci-stage.yml
    parameters:
      adfCodePath: "ETLSharedOps/SharedOps"
      adfPackageFilePath: "ETLPipelines/Shared"
      repoName: "ETLSharedOps"
