variables:
  serviceConnection: 'uc-esd-sub-sc-ETLOperations'
  commonPublishArmTemplateName: 'adfDemoArmTemplate'
  resourceGroupName: 'ucm-esd-dev-poc-shared-cus-rg-df-001'
  subscriptionId: '2c7fb6e6-2527-4c02-be25-68120768c342'
  dataFactoryName: 'ucmshareddevdfpoccus01'

  AzureBlobStorage1_properties_typeProperties_connectionString_secretName: "sadevpocadf-accesskey"

# Key Vault
  #keyVaultName: 'ucmesdsharedcusakv001'